name: mediasoup_client_flutter
description: Mediasoup client side Flutter library. Work for Android, iOS, MacOS, Windows and browser.
version: 0.9.0
homepage: https://github.com/Blancduman/mediasoup-client-flutter
repository: https://github.com/Blancduman/mediasoup-client-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.5+hotfix.1
  events2: ^1.0.0
  sdp_transform: ^0.3.2
  collection: ^1.18.0
  h264_profile_level_id: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
